from django.db import models


class User(models.Model):
    """
    Model representing a user in the application.

    Fields:
        username (str): The username of the user (max length: 50 characters).
        password (str): The password of the user (max length: 128 characters).
        email (str): The email address of the user (max length: 254 characters, unique).

    Methods:
        __str__: Returns a string representation of the user, which is their username.

    Attributes:
        id (int): The unique identifier of the user, automatically generated by Django.

    Note: Storing passwords as plain text is not recommended for security reasons. Consider using a secure password hashing library like Argon2 or bcrypt to store hashed passwords.

    """
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=128)  
    email = models.EmailField(max_length=254, unique=True)

    def __str__(self):
        return self.username
